### PR TITLE
refactored and commented recommendations.py

### PR DESCRIPTION
**Pull request by caseydailey**
# Refactored and commented recommendations.py

## Status

READY

## Description

i've added a few comments in an effort to clarify
the recommendations process and help a bit with readability
by reformatting some of the chained query sets

**i've changed a lot of variable names and restructured the data a bit for simplicity and readability**

## Related Tickets 

#23 

## Impacted Areas of the Application
Files that this PR modifies or affects in some way.
 
```
   modified:   website/views/recommendations.py
   modified:   website/templates/recommendations.html
```

i've  added comments and broken apart a few long lines.

**i've changed a lot of names, types, and structures.**

## Deploy Notes
Anything that a user needs to know in order to deploy/properly test this branch. Provide step by step instructions that address any db migrations, packages needed, ect. Be as specific as possible in your instructions

For example: 
```
    git pull 
    git fetch --all
    git checkout cjd-comment
    subl website/views/recommendations.py

```
review the comments to see that they make sense and are helpful

## Testing

Tests run?
 
YES

Are all tests passing?

YES

## READ_ME updates
Have you updated the README to reflect any relevant changes?
NO

### CODE REVIEW

**Comment by caseydailey** [comment]
i left a few print statements so you can see what's going on. 
the logic is the same. 
aside from changing some variables and method names, 
the main difference in the refactor
are the changes to the data-structures toward simplification mostly for the purpose of readability.

**Comment by caseydailey** [comment]
a couple of logical questions/concerns:

* we are excluding liked-but-not-purchased products from recommendations
* we are not excluding items that are relevant but already on an open order
** not sure if this is a problem since we list cart contents right below, but...
* if a product has been recommended by a friend and is in a category with at least some relevance, 
   maybe we should add a bit of relevance there?

and ideas:

* if a user has purchased a product and rated it above 3, should we recommend they buy it again or 
  as if they'd like to recommend it?
* if user A has purchased product X and user B has purchased product X and product Y,
  should we recommend product Y to user A? 
  maybe if user B rated Y above three and they both rated X above 3?

**Comment by taylorperkins** [comment]
Killer man!! Awesome work. I definitely approve, and it is great to keeping everything relevant to what youre using. 
Only a couple things. 
Go ahead and remove the commented out h3 tags in the template.
Also, remove any objects you're passing through the render that are no longer necessary to the page.

**Comment by taylorperkins** [comment]
sveet

**Pull request merged**
