### PR TITLE
Cjd troubleshooting

### PR DESCRIPTION
**Pull request by caseydailey**
# Trashy Armadillos Pull Request Template

## Status

READY

## Description
A description of what this PR does

* The link to view cart from index works now
* The link to view categories from index works now
* Ive also built in some exception and edge case handling. specifically:
   * when you have no payment types you can't go to checkout. 
   * if you have no products, you can't view your cart.
   * if you delete your only payment type, you'll be prompted to create a new one
   * a date completed is assigned when order is complete
   * finally, I've updated some doc-strings and commented the tricky bits of internal logic for clarity

## Related Tickets 
List all related tickets that are addressed by this pull request

this was a rogue housekeeping branch.

## Impacted Areas of the Application:

I was all over the place on this one: 

```
modified:   website/templates/index.html
modified:   website/templates/account/edit_payment.html
created:    website/templates/account/no_payment_type.html
created:    website/templates/account/no_order.html
modified:   website/templates/orders/view_order.html
modified:   website/templates/orders/order_complete.html
modified:   website/urls.py
modified:   website/views.py
	
```

## Deploy Notes

```
    git pull 
    git fetch --all
    git checkout cjd-troubleshooting
    ./refresh_database.sh
    python manage.py runserver
```

navigate to: http://127.0.0.1:8000/

verify that the functionality in the description is accomplished

### CODE REVIEW

**Comment by taylorperkins** [comment]
change line 333 in views.py to 
```
elif 'payment_type' in request.POST
```
Then remove line 334

in your edit_payment.html, include `value='Delete'` in your input tag on line 15

**Comment by short880** [comment]
#solid, #greatwork, #iDigitliketheguyoffofamericanidol

#but

#small stuff =>
  1) views.view_order => I left the <h1>product.id</h1> in the html document while trying to get products to correctly display and delete. I'll remove.
  2) views.edit_payment_type => submit button value is "submit".. needs to be "delete"
  
#bug =>
1) When the user clicks "cancel order" on views.view_orderis giving ERROR `The view website.views.view_order didn't return an HttpResponse object. It returned None instead.`
2)

**Comment by taylorperkins** [comment]
otherwise it's good:)

**Comment by taylorperkins** [comment]
#############################################

**Comment by short880** [comment]
good

**Comment by caseydailey** [comment]
great

**Comment by caseydailey** [comment]
#thanks dudes

**Pull request merged**
