### PR TITLE
Tp create recommendations

### PR DESCRIPTION
**Pull request by taylorperkins**
# Trashy Armadillos Pull Request Template

## Status
Is this PR ready to be looked at by other group members? 
    Yes

## Description
A description of what this PR does
    This pr serves as a recommendation engine for a specific user to recommend products that a user may like to purchase based off of previous purchase and like history

## Related Tickets 
List all related tickets that are addressed by this pull request
    https://github.com/Trashy-Armadillos/djangazon/issues/23

## Impacted Areas of the Application
Files that this PR modifies or affects in some way. 
```
    recommendations.py
    recommendations.html
    login_user.html
```

## Deploy Notes
Anything that a user needs to know in order to deploy/properly test this branch. Provide step by step instructions that address any db migrations, packages needed, ect. Be as specific as possible in your instructions

For example: 
```
    ./refresh_database.sh
    ./manage.py runserver
```

You want to create a new user instance, and like products. dislike products. Add products to your order, and purchase them. 
Be sure to understand the categories of the products you are buying/liking
logout, then log back in. You should have products recommended to you, as well as an open order displayed if you have an open order in the site.

## Testing
Tests run? Yes
Are all tests passing? Yes
If not, why?

## READ_ME updates
Have you updated the README to reflect any relevant changes?
    Nope

### CODE REVIEW

**Comment by caseydailey** [comment]
#hellyeah

**Comment by stevebrownlee** [comment]
@caseydailey @taylorperkins Was this code reviewed with the entire team?

**Comment by stevebrownlee** [comment]
Also, I noticed that the file `db.sqlite3.sqbpro` was checked in.  That will need to be removed.

**Comment by stevebrownlee** [comment]
@taylorperkins Also seeing quite a few lines of commented out code. Will need to remove that.

**Comment by stevebrownlee** [comment]
@taylorperkins Overall, great job of building the logic for this process. 
@caseydailey I would like your team to demo this code to the rest of your teammates on Monday

**Comment by taylorperkins** [comment]
@stevebrownlee It was not reviewed by the entire team. I believe Miriam saw it, but Casey was the one to check my PR for it. Justin had left before we finished it. 
We can be sure to remove the `db.sqlite.spbpro`
And I had wanted to leave in the print statements to show the rest of the team when we were all together. It makes it easier to see each step when explaining. However, they will be removed Monday. 
And thank you!! I loved learning how to implement this feature, and had a great time finishing it, however, I cannot take full credit for the logic. @caseydailey was right next to me the entire time for this ticket. It was definitely a team effort.

**Pull request merged**
