### PR TITLE
He add payment option

### PR DESCRIPTION
**Pull request by harryepstein**
Illegal Llamas Pull Request Template

## Status
Is this PR ready to be looked at by other group members? 
READY
## Description
A description of what this PR does
Allows the logged in user to visit their account information page and add a payment type for future use in orders
## Related Tickets 
List all related tickets that are addressed by this pull request

[A link to a ticket](link.com)

[A link to a ticket](link.com)

## Impacted Areas of the Application
Files that this PR modifies or affects in some way. 
```
    Views.py
    Models.py
    Urls.py
    Forms.py
    add_payment.html
```

## Deploy Notes
Anything that a user needs to know in order to deploy/properly test this branch. Provide step by step instructions that address any db migrations, packages needed, ect. Be as specific as possible in your instructions

For example: 
```
    git pull 
    git fetch --all
    git checkout example_branch_name
    python manage.py makemigration
    python manage.py migrate
    python manage.py runserver
```

## Testing
Tests run?
Are all tests passing?
If not, why?
Not tests yet
## READ_ME updates
Have you updated the README to reflect any relevant changes?

### CODE REVIEW

**Comment by caseydailey** [comment]
looks great! just make name required by removing "blank=true" form the model
and it should be good!

**Comment by caseydailey** [comment]
i just added a payment type with an account number "123" just check that the input requires account numbers to be realistic?

**Comment by short880** [comment]
👎

**Comment by short880** [comment]
Correction: 👍

**Pull request merged**
